feat: support config params in model execution
empirical-run/empirical pull request #70
Opened 2024-04-03 10:27 UTC by arjunattam

2024-04-03 14:34 UTC, arjunattam commented
updated based on our discussion, @saikatmitra91. i will push schema to cloudflare after #74

2024-04-03 17:32 UTC, saikatmitra91 requested changes

2024-04-03 17:32 UTC, saikatmitra91 commented on packages/ai/src/utils/index.ts
> +function isKnownParameter(paramName: string) {
```suggestion
function isReservedParameter(paramName: string) {
```

2024-04-03 17:32 UTC, saikatmitra91 commented on packages/ai/src/utils/index.ts
> +  const knownParameters = [
```suggestion
  const reservedParameters = [
```

2024-04-03 17:32 UTC, saikatmitra91 commented on packages/ai/src/utils/index.ts
> +  const otherFieldsToSkip = ["model", "messages"];
if we  rename the list to reserved, dont have to keep this as separate array ?

2024-04-03 17:32 UTC, saikatmitra91 commented on packages/ai/src/utils/index.ts
> +      body[key] = undefined;
why do we need to do this ?

2024-04-04 04:16 UTC, saikatmitra91 approved these changes

2024-04-04 04:16 UTC, merged